#!/usr/bin/env bun
/**
 * Write every app's `wrangler.jsonc` from the resource table in
 * `@seldon/foundation`.
 *
 * The generated files are committed — wrangler reads them, humans review
 * them, and `bun run infra:check` fails if they drift from the table or
 * from the synced Pulumi outputs.
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { SERVICE_NAMES, SERVICES } from "@seldon/foundation";
import { REPO_ROOT } from "./lib/config.js";
import { mustRun } from "./lib/run.js";
import { readAllStackOutputs } from "./lib/stack-outputs.js";
import { buildWranglerConfig } from "./lib/wrangler-config.js";

const outputs = readAllStackOutputs();
const written: string[] = [];

for (const service of SERVICE_NAMES) {
  const config = buildWranglerConfig(service, { outputs });
  const header = [
    `// apps/${service}/wrangler.jsonc — ${SERVICES[service].properName}.`,
    `// ${SERVICES[service].owns}.`,
    "//",
    "// GENERATED by `bun run gen:wrangler` from the resource table in",
    "// @seldon/foundation. Edit that table, not this file: `bun run",
    "// infra:check` fails on drift. Ids come from the synced Pulumi",
    "// stack outputs in infra/outputs/.",
    "",
  ].join("\n");
  const path = join(REPO_ROOT, "apps", service, "wrangler.jsonc");
  writeFileSync(path, `${header}${JSON.stringify(config, null, 2)}\n`);
  written.push(path);
  console.log(`wrote apps/${service}/wrangler.jsonc`);
}

// Format through Biome so a generated file and a formatted one are the
// same file, and `biome check` never fights `gen:wrangler`.
await mustRun(["bunx", "biome", "format", "--write", ...written], {
  cwd: REPO_ROOT,
  quiet: true,
});
